Repository Catch-y/Spring_BE, pull requests merged in 2025-01, with the labels that each got.

#3 feat: 응답통일, 공통 예외처리
  build.gradle
  src/main/java/umc/catchy/global/.gitkeep
  src/main/java/umc/catchy/global/common/response/BaseResponse.java
  src/main/java/umc/catchy/global/common/response/code/BaseCode.java
  src/main/java/umc/catchy/global/common/response/code/BaseErrorCode.java
  src/main/java/umc/catchy/global/common/response/code/ErrorReasonDTO.java
  src/main/java/umc/catchy/global/common/response/code/ReasonDTO.java
  src/main/java/umc/catchy/global/common/response/status/ErrorStatus.java
  src/main/java/umc/catchy/global/common/response/status/SuccessStatus.java
  src/main/java/umc/catchy/global/error/exception/ExceptionAdvice.java
  src/main/java/umc/catchy/global/error/exception/GeneralException.java
Labels: feat

#5 feat: Swagger 설정
  build.gradle
  src/main/java/umc/catchy/domain/group/domain/Groups.java
  src/main/java/umc/catchy/domain/like/domain/Likes.java
  src/main/java/umc/catchy/domain/mapping/memberGroup/domain/MemberGroup.java
  src/main/java/umc/catchy/domain/mapping/placeCourse/domain/PlaceCourse.java
  src/main/java/umc/catchy/domain/vote/domain/Vote.java
  src/main/java/umc/catchy/global/config/swagger/SwaggerConfig.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: feat

#10 [feature] CI/CD 파이프라인 구축
  .github/workflows/github-actions.yml
  Dockerfile
  build.gradle
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: feat

#12 [feature] 소셜 로그인 및 토큰 재발급
  build.gradle
  src/main/java/umc/catchy/CatchyApplication.java
  src/main/java/umc/catchy/domain/jwt/domain/TokenProvider.java
  src/main/java/umc/catchy/domain/member/api/.gitkeep
  src/main/java/umc/catchy/domain/member/api/MemberController.java
  src/main/java/umc/catchy/domain/member/dao/.gitkeep
  src/main/java/umc/catchy/domain/member/dao/MemberRepository.java
  src/main/java/umc/catchy/domain/member/domain/Member.java
  src/main/java/umc/catchy/domain/member/dto/.gitkeep
  src/main/java/umc/catchy/domain/member/dto/request/LoginRequest.java
  src/main/java/umc/catchy/domain/member/dto/request/ReIssueTokenRequest.java
  src/main/java/umc/catchy/domain/member/dto/request/SignUpRequest.java
  src/main/java/umc/catchy/domain/member/dto/response/LoginResponse.java
  src/main/java/umc/catchy/domain/member/dto/response/ReIssueTokenResponse.java
  src/main/java/umc/catchy/domain/member/dto/response/SignUpResponse.java
  src/main/java/umc/catchy/domain/member/service/.gitkeep
  src/main/java/umc/catchy/domain/member/service/MemberService.java
  src/main/java/umc/catchy/global/common/constants/RegexConstants.java
  src/main/java/umc/catchy/global/common/response/status/ErrorStatus.java
  src/main/java/umc/catchy/global/converter/OctetStreamReadMsgConverter.java
  src/main/java/umc/catchy/global/error/exception/ExceptionAdvice.java
  src/main/java/umc/catchy/global/util/JWTUtil.java
  src/main/java/umc/catchy/infra/.gitkeep
  src/main/java/umc/catchy/infra/config/jwt/JWTProperties.java
  src/main/resources/application-prod.yml
Labels: feat

#17 [feature] Spring Security 구현
  src/main/java/umc/catchy/domain/jwt/domain/JwtTokenProvider.java
  src/main/java/umc/catchy/domain/jwt/domain/TokenProvider.java
  src/main/java/umc/catchy/domain/member/api/MemberController.java
  src/main/java/umc/catchy/domain/member/dao/MemberRepository.java
  src/main/java/umc/catchy/domain/member/service/MemberService.java
  src/main/java/umc/catchy/global/common/response/status/ErrorStatus.java
  src/main/java/umc/catchy/global/config/security/SecurityConfig.java
  src/main/java/umc/catchy/global/util/JWTUtil.java
  src/main/java/umc/catchy/global/util/JwtUtil.java
  src/main/java/umc/catchy/global/util/SecurityUtil.java
  src/main/java/umc/catchy/infra/config/jwt/JwtProperties.java
  src/main/java/umc/catchy/infra/config/security/JwtAuthenticationFilter.java
  src/main/java/umc/catchy/infra/config/security/JwtExceptionFilter.java
Labels: feat

#19 [feature] 개인정보(프로필) 조회 및 수정
  src/main/java/umc/catchy/domain/member/api/MemberController.java
  src/main/java/umc/catchy/domain/member/domain/Member.java
  src/main/java/umc/catchy/domain/member/dto/request/ProfileRequest.java
  src/main/java/umc/catchy/domain/member/dto/response/ProfileResponse.java
  src/main/java/umc/catchy/domain/member/service/MemberService.java
Labels: feat

#24 [feature] 그룹-그룹 생성하기
  src/main/java/umc/catchy/domain/group/api/GroupController.java
  src/main/java/umc/catchy/domain/group/dto/request/CreateGroupRequest.java
  src/main/java/umc/catchy/domain/group/dto/response/CreateGroupResponse.java
  src/main/java/umc/catchy/domain/group/service/GroupService.java
  src/main/resources/application-local.yml
Labels: feat

#26 [feature] 취향설문 1,2단계 설정
  src/main/java/umc/catchy/domain/category/dao/CategoryRepository.java
  src/main/java/umc/catchy/domain/category/dto/request/CategorySurveyRequest.java
  src/main/java/umc/catchy/domain/categoryVote/domain/CategoryVote.java
  src/main/java/umc/catchy/domain/mapping/memberCategory/dao/MemberCategoryRepository.java
  src/main/java/umc/catchy/domain/mapping/memberCategory/domain/MemberCategory.java
  src/main/java/umc/catchy/domain/mapping/memberCategory/dto/response/MemberCategoryCreatedResponse.java
  src/main/java/umc/catchy/domain/member/api/MemberController.java
  src/main/java/umc/catchy/domain/member/service/MemberService.java
  src/main/resources/application-local.yml
Labels: feat

#25 [feature] S3 연결 및 이미지 업로드 기능 구현
  .github/workflows/github-actions.yml
  Dockerfile
  build.gradle
  src/main/java/umc/catchy/domain/Uuid/api/ImageController.java
  src/main/java/umc/catchy/domain/Uuid/dao/UuidRepository.java
  src/main/java/umc/catchy/domain/Uuid/domain/Uuid.java
  src/main/java/umc/catchy/domain/Uuid/service/S3Service.java
  src/main/java/umc/catchy/domain/member/service/MemberService.java
  src/main/java/umc/catchy/global/config/s3/AmazonConfig.java
  src/main/java/umc/catchy/infra/aws/s3/AmazonS3Manager.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: feat

#32 [feature] 취향설문 3,4단계 (참여 스타일 및 요일, 시간)
  .gitignore
  src/main/java/umc/catchy/domain/activetime/dao/ActiveTimeRepository.java
  src/main/java/umc/catchy/domain/activetime/domain/ActiveTime.java
  src/main/java/umc/catchy/domain/category/domain/BigCategory.java
  src/main/java/umc/catchy/domain/mapping/memberActivetime/dao/MemberActiveTimeRepository.java
  src/main/java/umc/catchy/domain/mapping/memberActivetime/domain/MemberActiveTime.java
  src/main/java/umc/catchy/domain/mapping/memberStyle/dao/MemberStyleRepository.java
  src/main/java/umc/catchy/domain/mapping/memberStyle/domain/MemberStyle.java
  src/main/java/umc/catchy/domain/member/api/MemberController.java
  src/main/java/umc/catchy/domain/member/dto/request/StyleAndActiveTimeSurveyRequest.java
  src/main/java/umc/catchy/domain/member/dto/response/StyleAndActiveTimeSurveyCreatedResponse.java
  src/main/java/umc/catchy/domain/member/service/MemberService.java
  src/main/java/umc/catchy/domain/style/dao/StyleRepository.java
  src/main/java/umc/catchy/domain/style/domain/StyleName.java
  src/main/resources/application-local.yml
Labels: feat

#34 [feature] 그룹 탈퇴
  src/main/java/umc/catchy/domain/group/api/GroupController.java
  src/main/java/umc/catchy/domain/group/service/GroupService.java
  src/main/java/umc/catchy/domain/mapping/memberGroup/dao/MemberGroupRepository.java
  src/main/java/umc/catchy/global/common/response/status/ErrorStatus.java
Labels: feat

#36 [feature] 캘린더-그룹 조회
  src/main/java/umc/catchy/domain/group/api/GroupController.java
  src/main/java/umc/catchy/domain/group/dto/response/GroupCalendarResponse.java
  src/main/java/umc/catchy/domain/group/service/GroupService.java
  src/main/java/umc/catchy/domain/mapping/memberGroup/dao/MemberGroupRepository.java
Labels: feat

#40 [feature] 투표 생성하기
  src/main/java/umc/catchy/domain/vote/api/VoteController.java
  src/main/java/umc/catchy/domain/vote/dao/VoteRepository.java
  src/main/java/umc/catchy/domain/vote/domain/Vote.java
  src/main/java/umc/catchy/domain/vote/dto/request/CreateVoteRequest.java
  src/main/java/umc/catchy/domain/vote/dto/response/VoteResponse.java
  src/main/java/umc/catchy/domain/vote/service/VoteService.java
Labels: feat

#39 [feature] 사용자 취향설문 5단계(선호 지역)
  .gitignore
  src/main/java/umc/catchy/domain/location/dao/LocationRepository.java
  src/main/java/umc/catchy/domain/location/domain/Location.java
  src/main/java/umc/catchy/domain/location/dto/request/LocationSurveyRequest.java
  src/main/java/umc/catchy/domain/mapping/memberLocation/dao/MemberLocationRepository.java
  src/main/java/umc/catchy/domain/mapping/memberLocation/domain/MemberLocation.java
  src/main/java/umc/catchy/domain/mapping/memberLocation/dto/response/MemberLocationCreatedResponse.java
  src/main/java/umc/catchy/domain/member/api/MemberController.java
  src/main/java/umc/catchy/domain/member/service/MemberService.java
  src/main/resources/application-local.yml
Labels: feat

#43 [feature] 회원 탈퇴, 토큰 검사 및 재발급
  src/main/java/umc/catchy/domain/member/api/MemberController.java
  src/main/java/umc/catchy/domain/member/domain/Member.java
  src/main/java/umc/catchy/domain/member/dto/request/SignUpRequest.java
  src/main/java/umc/catchy/domain/member/dto/response/AppleAuthTokenResponse.java
  src/main/java/umc/catchy/domain/member/service/MemberService.java
  src/main/java/umc/catchy/global/common/response/status/ErrorStatus.java
  src/main/java/umc/catchy/global/config/security/SecurityConfig.java
  src/main/java/umc/catchy/global/config/swagger/SwaggerConfig.java
  src/main/java/umc/catchy/global/util/SecurityUtil.java
Labels: feat

#46 [feature] 코스 상세 정보 조회 API
  src/main/java/umc/catchy/domain/course/api/CourseController.java
  src/main/java/umc/catchy/domain/course/converter/CourseConverter.java
  src/main/java/umc/catchy/domain/course/dao/CourseRepository.java
  src/main/java/umc/catchy/domain/course/domain/Course.java
  src/main/java/umc/catchy/domain/course/dto/request/.gitkeep
  src/main/java/umc/catchy/domain/course/dto/response/CourseInfoResponse.java
  src/main/java/umc/catchy/domain/course/service/CourseService.java
  src/main/java/umc/catchy/domain/courseReview/dao/CourseReviewRepository.java
  src/main/java/umc/catchy/domain/mapping/placeCourse/dao/PlaceCourseRepository.java
  src/main/java/umc/catchy/domain/mapping/placeVisit/dao/PlaceVisitRepository.java
  src/main/java/umc/catchy/domain/place/converter/PlaceConverter.java
  src/main/java/umc/catchy/global/common/response/status/ErrorStatus.java
Labels: feat

#48 [refactor] application.yml 인텔리제이에서 환경 변수를 주입하도록 개선
  .DS_Store
  .gitignore
  src/.DS_Store
  src/main/.DS_Store
  src/main/resources/application-local.yml
Labels: refactor

#50 [feature] 카테고리 투표하기
  src/main/java/umc/catchy/domain/categoryVote/dao/CategoryVoteRepository.java
  src/main/java/umc/catchy/domain/categoryVote/domain/CategoryVote.java
  src/main/java/umc/catchy/domain/mapping/memberCategoryVote/dao/MemberCategoryVoteRepository.java
  src/main/java/umc/catchy/domain/mapping/memberCategoryVote/domain/MemberCategoryVote.java
  src/main/java/umc/catchy/domain/mapping/memberGroup/dao/MemberGroupRepository.java
  src/main/java/umc/catchy/domain/vote/api/VoteController.java
  src/main/java/umc/catchy/domain/vote/domain/Vote.java
  src/main/java/umc/catchy/domain/vote/dto/request/SubmitVoteRequest.java
  src/main/java/umc/catchy/domain/vote/dto/response/CategoryDto.java
  src/main/java/umc/catchy/domain/vote/dto/response/CategoryResponse.java
  src/main/java/umc/catchy/domain/vote/dto/response/GroupVoteStatusResponse.java
  src/main/java/umc/catchy/domain/vote/dto/response/MemberVoteStatus.java
  src/main/java/umc/catchy/domain/vote/dto/response/VoteResult.java
  src/main/java/umc/catchy/domain/vote/dto/response/VoteResultResponse.java
  src/main/java/umc/catchy/domain/vote/dto/response/VotedMemberResponse.java
  src/main/java/umc/catchy/domain/vote/service/VoteService.java
  src/main/java/umc/catchy/global/common/response/status/ErrorStatus.java
Labels: feat

#55 [feature] 장소 평점/리뷰 POST 기능 구현
  src/main/java/umc/catchy/domain/course/converter/CourseConverter.java
  src/main/java/umc/catchy/domain/course/domain/Course.java
  src/main/java/umc/catchy/domain/course/dto/response/CourseInfoResponse.java
  src/main/java/umc/catchy/domain/course/service/CourseService.java
  src/main/java/umc/catchy/domain/mapping/placeVisit/domain/PlaceVisit.java
  src/main/java/umc/catchy/domain/place/api/PlaceController.java
  src/main/java/umc/catchy/domain/place/dao/PlaceRepository.java
  src/main/java/umc/catchy/domain/place/domain/Place.java
  src/main/java/umc/catchy/domain/placeReview/converter/PlaceReviewConverter.java
  src/main/java/umc/catchy/domain/placeReview/dao/PlaceReviewRepository.java
  src/main/java/umc/catchy/domain/placeReview/domain/PlaceReview.java
  src/main/java/umc/catchy/domain/placeReview/dto/request/PostPlaceReviewRequest.java
  src/main/java/umc/catchy/domain/placeReview/dto/response/PostPlaceReviewResponse.java
  src/main/java/umc/catchy/domain/placeReview/service/PlaceReviewService.java
  src/main/java/umc/catchy/domain/placeReviewImage/converter/PlaceReviewImageConverter.java
  src/main/java/umc/catchy/domain/placeReviewImage/dao/PlaceReviewImageRepository.java
  src/main/java/umc/catchy/domain/placeReviewImage/domain/PlaceReviewImage.java
  src/main/java/umc/catchy/global/common/response/status/ErrorStatus.java
Labels: feat

#53 [fix] 중복 투표 방지 검증
  src/main/java/umc/catchy/domain/vote/service/VoteService.java
Labels: fix

#58 [feature] 코스 리뷰 작성 API
  src/main/java/umc/catchy/domain/course/api/CourseController.java
  src/main/java/umc/catchy/domain/course/domain/Course.java
  src/main/java/umc/catchy/domain/courseReview/converter/CourseReviewConverter.java
  src/main/java/umc/catchy/domain/courseReview/dao/CourseReviewRepository.java
  src/main/java/umc/catchy/domain/courseReview/domain/CourseReview.java
  src/main/java/umc/catchy/domain/courseReview/dto/request/PostCourseReviewRequest.java
  src/main/java/umc/catchy/domain/courseReview/dto/response/PostCourseReviewResponse.java
  src/main/java/umc/catchy/domain/courseReview/service/CourseReviewService.java
  src/main/java/umc/catchy/domain/courseReviewImage/converter/CourseReviewImageConverter.java
  src/main/java/umc/catchy/domain/courseReviewImage/dao/CourseReviewImageRepository.java
  src/main/java/umc/catchy/domain/courseReviewImage/domain/CourseReviewImage.java
  src/main/java/umc/catchy/domain/mapping/memberCourse/dao/MemberCourseRepository.java
  src/main/java/umc/catchy/domain/mapping/memberCourse/domain/MemberCourse.java
  src/main/java/umc/catchy/domain/placeReview/service/PlaceReviewService.java
  src/main/java/umc/catchy/global/common/response/status/ErrorStatus.java
Labels: feat

#59 [feature] 사용자의 코스 조회
  src/main/java/umc/catchy/domain/course/api/CourseController.java
  src/main/java/umc/catchy/domain/course/service/CourseService.java
  src/main/java/umc/catchy/domain/mapping/memberCourse/converter/MemberCourseConverter.java
  src/main/java/umc/catchy/domain/mapping/memberCourse/dao/MemberCourseRepository.java
  src/main/java/umc/catchy/domain/mapping/memberCourse/dto/response/MemberCourseResponse.java
  src/main/java/umc/catchy/global/common/response/status/ErrorStatus.java
Labels: feat

#68 [feature] 코스 찜하기
  src/main/java/umc/catchy/domain/course/api/CourseController.java
  src/main/java/umc/catchy/domain/mapping/memberCourse/dao/MemberCourseRepository.java
  src/main/java/umc/catchy/domain/mapping/memberCourse/domain/MemberCourse.java
  src/main/java/umc/catchy/domain/mapping/memberCourse/dto/response/CourseBookmarkResponse.java
  src/main/java/umc/catchy/domain/mapping/memberCourse/service/MemberCourseService.java
  src/main/java/umc/catchy/global/common/response/status/ErrorStatus.java
  src/main/resources/application-local.yml
Labels: feat

#69 [feature] 장소 좋아요
  src/main/java/umc/catchy/domain/mapping/placeVisit/dao/PlaceVisitRepository.java
  src/main/java/umc/catchy/domain/mapping/placeVisit/domain/PlaceVisit.java
  src/main/java/umc/catchy/domain/mapping/placeVisit/dto/response/PlaceLikedResponse.java
  src/main/java/umc/catchy/domain/mapping/placeVisit/service/PlaceVisitService.java
  src/main/java/umc/catchy/domain/place/api/PlaceController.java
Labels: feat

#63 [fix] 코스 평점 계산 로직 추가
  src/main/java/umc/catchy/domain/mapping/placeCourse/dao/PlaceCourseRepository.java
  src/main/java/umc/catchy/domain/placeReview/service/PlaceReviewService.java
Labels: feat, fix

#73 [feature] 투표 완료 카테고리, 장소 확인
  src/main/java/umc/catchy/domain/category/dao/CategoryRepository.java
  src/main/java/umc/catchy/domain/categoryVote/dao/CategoryVoteRepository.java
  src/main/java/umc/catchy/domain/categoryVote/domain/CategoryVote.java
  src/main/java/umc/catchy/domain/group/domain/Groups.java
  src/main/java/umc/catchy/domain/mapping/memberCategoryVote/dao/MemberCategoryVoteRepository.java
  src/main/java/umc/catchy/domain/place/dao/PlaceRepository.java
  src/main/java/umc/catchy/domain/placeReview/dao/PlaceReviewRepository.java
  src/main/java/umc/catchy/domain/vote/api/VoteController.java
  src/main/java/umc/catchy/domain/vote/dto/response/CategoryResult.java
  src/main/java/umc/catchy/domain/vote/dto/response/GroupPlaceResponse.java
  src/main/java/umc/catchy/domain/vote/dto/response/GroupVoteResultResponse.java
  src/main/java/umc/catchy/domain/vote/dto/response/PlaceResponse.java
  src/main/java/umc/catchy/domain/vote/dto/response/VoteResultResponse.java
  src/main/java/umc/catchy/domain/vote/service/VoteService.java
Labels: feat

#64 [feature] 코스 수정, 삭제, 생성(DIY), 조회(페이징)
  src/main/java/umc/catchy/domain/course/api/CourseController.java
  src/main/java/umc/catchy/domain/course/converter/CourseConverter.java
  src/main/java/umc/catchy/domain/course/dao/CourseRepository.java
  src/main/java/umc/catchy/domain/course/dao/CourseRepositoryCustom.java
  src/main/java/umc/catchy/domain/course/dao/CourseRepositoryImpl.java
  src/main/java/umc/catchy/domain/course/domain/Course.java
  src/main/java/umc/catchy/domain/course/dto/request/.gitkeep
  src/main/java/umc/catchy/domain/course/dto/request/CourseCreateRequest.java
  src/main/java/umc/catchy/domain/course/dto/request/CourseUpdateRequest.java
  src/main/java/umc/catchy/domain/course/service/CourseService.java
  src/main/java/umc/catchy/domain/mapping/memberCourse/converter/MemberCourseConverter.java
  src/main/java/umc/catchy/domain/mapping/memberCourse/domain/MemberCourse.java
  src/main/java/umc/catchy/domain/mapping/memberCourse/dto/response/MemberCourseResponse.java
  src/main/java/umc/catchy/domain/mapping/placeCourse/domain/PlaceCourse.java
  src/main/java/umc/catchy/global/common/response/status/ErrorStatus.java
  src/main/java/umc/catchy/infra/config/security/JwtExceptionFilter.java
Labels: feat, fix

#75 [feature] 장소 투표하기
  src/main/java/umc/catchy/domain/categoryVote/domain/CategoryVote.java
  src/main/java/umc/catchy/domain/mapping/memberPlaceVote/dao/MemberPlaceVoteRepository.java
  src/main/java/umc/catchy/domain/mapping/memberPlaceVote/domain/MemberPlaceVote.java
  src/main/java/umc/catchy/domain/placeVote/dao/PlaceVoteRepository.java
  src/main/java/umc/catchy/domain/vote/api/VoteController.java
  src/main/java/umc/catchy/domain/vote/dto/request/PlaceVoteRequest.java
  src/main/java/umc/catchy/domain/vote/dto/response/PlaceResponse.java
  src/main/java/umc/catchy/domain/vote/service/VoteService.java
  src/main/java/umc/catchy/global/common/response/status/ErrorStatus.java
Labels: feat

#87 [fix] 장소 카테고리 매핑관계 수정
  src/main/java/umc/catchy/domain/place/domain/Place.java
Labels: fix

#84 [feature] 장소 검색 및 상세 정보 보기
  src/main/java/umc/catchy/domain/mapping/placeCourse/api/PlaceCourseController.java
  src/main/java/umc/catchy/domain/mapping/placeCourse/dto/response/PlaceInfo.java
  src/main/java/umc/catchy/domain/mapping/placeCourse/dto/response/PlaceInfoDetail.java
  src/main/java/umc/catchy/domain/mapping/placeCourse/service/PlaceCourseService.java
  src/main/java/umc/catchy/domain/member/dto/response/SignUpResponse.java
  src/main/java/umc/catchy/domain/place/converter/PlaceConverter.java
  src/main/java/umc/catchy/domain/place/dao/PlaceRepository.java
  src/main/java/umc/catchy/domain/place/domain/Place.java
  src/main/java/umc/catchy/global/common/response/status/ErrorStatus.java
  src/main/resources/application-prod.yml
Labels: feat

#94 [fix] 내 위치 기반 검색 안되던 오류 수정
  src/main/java/umc/catchy/domain/mapping/placeCourse/service/PlaceCourseService.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: fix

#82 [feature] 찜한 코스 조회
  src/main/java/umc/catchy/domain/mapping/memberCourse/api/MemberCourseController.java
  src/main/java/umc/catchy/domain/mapping/memberCourse/dao/MemberCourseRepository.java
  src/main/java/umc/catchy/domain/mapping/memberCourse/dao/MemberCourseRepositoryCustom.java
  src/main/java/umc/catchy/domain/mapping/memberCourse/dao/MemberCourseRepositoryImpl.java
  src/main/java/umc/catchy/domain/mapping/memberCourse/dto/response/MemberCourseResponse.java
  src/main/java/umc/catchy/domain/mapping/memberCourse/service/MemberCourseService.java
Labels: feat

#88 [feature] 좋아요한 장소 조회
  src/main/java/umc/catchy/domain/mapping/placeCourse/api/PlaceCourseController.java
  src/main/java/umc/catchy/domain/mapping/placeCourse/dao/PlaceCourseRepository.java
  src/main/java/umc/catchy/domain/mapping/placeCourse/dao/PlaceCourseRepositoryCustom.java
  src/main/java/umc/catchy/domain/mapping/placeCourse/dao/PlaceCourseRepositoryImpl.java
  src/main/java/umc/catchy/domain/mapping/placeCourse/dto/response/PlaceInfoResponse.java
  src/main/java/umc/catchy/domain/mapping/placeCourse/service/PlaceCourseService.java
Labels: feat

#96 [fix] 스크롤 응답 구조 통일
  src/main/java/umc/catchy/domain/mapping/memberCourse/api/MemberCourseController.java
  src/main/java/umc/catchy/domain/mapping/memberCourse/dto/response/MemberCourseSliceResponse.java
  src/main/java/umc/catchy/domain/mapping/memberCourse/service/MemberCourseService.java
  src/main/java/umc/catchy/domain/mapping/placeCourse/api/PlaceCourseController.java
  src/main/java/umc/catchy/domain/mapping/placeCourse/dto/response/PlaceInfoSliceResponse.java
  src/main/java/umc/catchy/domain/mapping/placeCourse/service/PlaceCourseService.java
Labels: fix

#92 [chore] OSRM 서버 구축 with Docker-compose
  .github/workflows/github-actions.yml
  docker-compose.yml
  src/main/java/umc/catchy/global/config/s3/AmazonConfig.java
  src/main/java/umc/catchy/infra/osrm/OsrmRequest.java
  src/main/java/umc/catchy/infra/osrm/OsrmResponse.java
  src/main/java/umc/catchy/infra/osrm/OsrmRouteController.java
  src/main/java/umc/catchy/infra/osrm/OsrmService.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: feat

#100 [feature] AI 추천 코스 생성
  build.gradle
  src/main/java/umc/catchy/domain/course/api/CourseController.java
  src/main/java/umc/catchy/domain/course/dto/response/GptCourseInfoResponse.java
  src/main/java/umc/catchy/domain/course/service/CourseService.java
  src/main/java/umc/catchy/domain/course/util/LocationUtils.java
  src/main/java/umc/catchy/domain/mapping/memberActivetime/dao/MemberActiveTimeRepository.java
  src/main/java/umc/catchy/domain/mapping/memberCategory/dao/MemberCategoryRepository.java
  src/main/java/umc/catchy/domain/mapping/memberLocation/dao/MemberLocationRepository.java
  src/main/java/umc/catchy/domain/mapping/memberStyle/dao/MemberStyleRepository.java
  src/main/java/umc/catchy/domain/place/dao/PlaceRepository.java
  src/main/java/umc/catchy/domain/style/domain/Style.java
  src/main/java/umc/catchy/global/common/response/status/ErrorStatus.java
  src/main/java/umc/catchy/global/error/exception/GeneralException.java
  src/main/java/umc/catchy/infra/aws/s3/AmazonS3Manager.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: feat

#101 [fix] 장소 및 코스 조회 response 변경
  src/main/java/umc/catchy/domain/course/api/CourseController.java
  src/main/java/umc/catchy/domain/course/dao/CourseRepository.java
  src/main/java/umc/catchy/domain/course/dao/CourseRepositoryCustom.java
  src/main/java/umc/catchy/domain/course/dao/CourseRepositoryImpl.java
  src/main/java/umc/catchy/domain/course/service/CourseService.java
  src/main/java/umc/catchy/domain/mapping/memberCourse/converter/MemberCourseConverter.java
  src/main/java/umc/catchy/domain/mapping/memberCourse/dao/MemberCourseRepositoryCustom.java
  src/main/java/umc/catchy/domain/mapping/memberCourse/dao/MemberCourseRepositoryImpl.java
  src/main/java/umc/catchy/domain/mapping/memberCourse/dto/response/MemberCourseResponse.java
  src/main/java/umc/catchy/domain/mapping/memberCourse/dto/response/MemberCourseSliceResponse.java
  src/main/java/umc/catchy/domain/mapping/placeCourse/api/PlaceCourseController.java
  src/main/java/umc/catchy/domain/mapping/placeCourse/dto/response/PlaceInfoDetail.java
  src/main/java/umc/catchy/domain/mapping/placeCourse/dto/response/PlaceInfoPreview.java
  src/main/java/umc/catchy/domain/mapping/placeCourse/dto/response/PlaceInfoPreviewResponse.java
  src/main/java/umc/catchy/domain/mapping/placeCourse/service/PlaceCourseService.java
  src/main/java/umc/catchy/domain/place/converter/PlaceConverter.java
Labels: fix

#105 [fix] 불필요한 import 제거
  src/main/java/umc/catchy/domain/course/service/CourseService.java
Labels: fix

#107 [fix] AI 추천 코스 이미지 생성
  src/main/java/umc/catchy/domain/course/service/CourseService.java
  src/main/java/umc/catchy/infra/aws/s3/AmazonS3Manager.java
Labels: fix

#109 [fix] 그룹 생성 - promiseTime을 LocalDateTime 형식으로 처리
  src/main/java/umc/catchy/domain/group/dto/request/CreateGroupRequest.java
  src/main/java/umc/catchy/domain/group/service/GroupService.java
Labels: fix

#111 [fix] 코스 평점
  src/main/java/umc/catchy/domain/course/dto/response/GptCourseInfoResponse.java
  src/main/java/umc/catchy/domain/course/service/CourseService.java
Labels: fix

#115 [feature] 장소 카테고리 지정 API 구현
  src/main/java/umc/catchy/domain/category/domain/BigCategory.java
  src/main/java/umc/catchy/domain/category/domain/Category.java
  src/main/java/umc/catchy/domain/course/api/CourseController.java
  src/main/java/umc/catchy/domain/mapping/placeCourse/api/PlaceCourseController.java
  src/main/java/umc/catchy/domain/mapping/placeCourse/dto/response/PlaceInfoPreview.java
  src/main/java/umc/catchy/domain/mapping/placeCourse/service/PlaceCourseService.java
  src/main/java/umc/catchy/domain/place/converter/PlaceConverter.java
  src/main/java/umc/catchy/domain/place/domain/Place.java
  src/main/java/umc/catchy/domain/place/dto/request/SetCategoryRequest.java
  src/main/java/umc/catchy/domain/place/service/PlaceService.java
  src/main/java/umc/catchy/global/common/response/status/ErrorStatus.java
Labels: feat

#112 [chore] 소셜 로그인 환경변수 설정
  build.gradle
  src/main/java/umc/catchy/domain/member/api/MemberController.java
  src/main/java/umc/catchy/domain/member/dto/response/AppleAuthTokenResponse.java
  src/main/java/umc/catchy/domain/member/dto/response/AppleLoginResponse.java
  src/main/java/umc/catchy/domain/member/dto/response/KakaoLoginResponse.java
  src/main/java/umc/catchy/domain/member/service/MemberService.java
  src/main/java/umc/catchy/global/common/response/status/ErrorStatus.java
  src/main/java/umc/catchy/global/config/security/SecurityConfig.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: fix

#117 [fix] enum 출력 형식 변경
  src/main/java/umc/catchy/domain/course/domain/CourseType.java
  src/main/java/umc/catchy/domain/course/service/CourseService.java
  src/main/java/umc/catchy/domain/mapping/memberCourse/dao/MemberCourseRepositoryImpl.java
  src/main/java/umc/catchy/domain/mapping/memberCourse/dto/response/MemberCourseResponse.java
Labels: fix

#119 [fix] AI 추천 코스 - 필터링 적용
  src/main/java/umc/catchy/domain/category/dao/CategoryRepository.java
  src/main/java/umc/catchy/domain/course/service/CourseService.java
  src/main/java/umc/catchy/domain/mapping/placeVisit/dao/PlaceVisitRepository.java
  src/main/java/umc/catchy/domain/place/dao/PlaceCustomRepository.java
  src/main/java/umc/catchy/domain/place/dao/PlaceRepository.java
  src/main/java/umc/catchy/domain/place/dao/PlaceRepositoryImpl.java
Labels: fix

#129 [feature] 개인 맞춤 코스 추천 섹션
  build.gradle
  dump.rdb
  src/main/java/umc/catchy/domain/course/api/CourseController.java
  src/main/java/umc/catchy/domain/course/converter/CourseTypeConverter.java
  src/main/java/umc/catchy/domain/course/dao/CourseRepository.java
  src/main/java/umc/catchy/domain/course/domain/Course.java
  src/main/java/umc/catchy/domain/course/dto/response/CourseRecommendationResponse.java
  src/main/java/umc/catchy/domain/course/dto/response/GptCourseInfoResponse.java
  src/main/java/umc/catchy/domain/course/service/CourseService.java
  src/main/java/umc/catchy/domain/course/service/GPTCourseService.java
  src/main/java/umc/catchy/domain/mapping/placeCourse/domain/PlaceCourse.java
  src/main/java/umc/catchy/global/common/response/status/ErrorStatus.java
  src/main/java/umc/catchy/global/config/gpt/OpenAiConfig.java
  src/main/java/umc/catchy/global/config/redis/RedisConfig.java
  src/main/java/umc/catchy/global/config/security/SecurityConfig.java
  src/main/java/umc/catchy/infra/gpt/ChatGPTRequest.java
  src/main/java/umc/catchy/infra/gpt/ChatGPTResponse.java
  src/main/java/umc/catchy/infra/gpt/CustomBotController.java
  src/main/java/umc/catchy/infra/gpt/Message.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: feat

#127 [feature] 리뷰 작성 시 방문 일자 조회
  src/main/java/umc/catchy/domain/mapping/placeVisit/dao/PlaceVisitRepository.java
  src/main/java/umc/catchy/domain/mapping/placeVisit/domain/PlaceVisit.java
  src/main/java/umc/catchy/domain/mapping/placeVisit/dto/response/PlaceVisitedDateResponse.java
  src/main/java/umc/catchy/domain/mapping/placeVisit/service/PlaceVisitService.java
  src/main/java/umc/catchy/domain/place/api/PlaceController.java
  src/main/java/umc/catchy/domain/placeReview/converter/PlaceReviewConverter.java
  src/main/java/umc/catchy/domain/placeReview/dto/response/PostPlaceReviewResponse.java
  src/main/java/umc/catchy/domain/placeReview/service/PlaceReviewService.java
Labels: feat

#138 [fix] 리뷰 작성 : 방문 날짜 로직 수정
  src/main/java/umc/catchy/domain/courseReview/converter/CourseReviewConverter.java
  src/main/java/umc/catchy/domain/courseReview/dto/response/PostCourseReviewResponse.java
  src/main/java/umc/catchy/domain/courseReview/service/CourseReviewService.java
  src/main/java/umc/catchy/domain/placeReview/converter/PlaceReviewConverter.java
  src/main/java/umc/catchy/domain/placeReview/domain/PlaceReview.java
  src/main/java/umc/catchy/domain/placeReview/dto/request/PostPlaceReviewRequest.java
  src/main/java/umc/catchy/domain/placeReview/dto/response/PostPlaceReviewResponse.java
  src/main/java/umc/catchy/domain/placeReview/service/PlaceReviewService.java
Labels: fix

#133 [fix] 그룹 내 투표 조회 검증
  src/main/java/umc/catchy/domain/vote/dao/VoteRepository.java
  src/main/java/umc/catchy/domain/vote/service/VoteService.java
  src/main/java/umc/catchy/global/common/response/status/ErrorStatus.java
Labels: fix

#137 [feature] 커스텀 예외 추가
  src/main/java/umc/catchy/global/common/response/BaseResponse.java
  src/main/java/umc/catchy/global/error/exception/ExceptionAdvice.java
  src/main/java/umc/catchy/global/error/exception/ResultEmptyListException.java
Labels: feat

#122 [fix] 코스 생성(DIY) 시 평점 계산 로직 추가
  src/main/java/umc/catchy/domain/course/converter/CourseConverter.java
  src/main/java/umc/catchy/domain/course/service/CourseService.java
Labels: fix
