Repository Catch-y/Spring_BE, pull requests merged in 2025-02, with the labels that each got.

#141 [fix] Course 도메인 @Enumerated(EnumType.STRING) 변경
  src/main/java/umc/catchy/domain/course/domain/Course.java
  src/main/java/umc/catchy/domain/course/service/CourseService.java
Labels: fix

#145 [chore] SwaggerConfig 설정
  src/main/java/umc/catchy/global/config/swagger/SwaggerConfig.java
Labels: chore

#130 [feature] 인기 코스(top10) 조회
  src/main/java/umc/catchy/domain/course/api/CourseController.java
  src/main/java/umc/catchy/domain/course/converter/CourseConverter.java
  src/main/java/umc/catchy/domain/course/dao/CourseRepository.java
  src/main/java/umc/catchy/domain/course/dao/CourseRepositoryCustom.java
  src/main/java/umc/catchy/domain/course/dao/CourseRepositoryImpl.java
  src/main/java/umc/catchy/domain/course/dto/response/PopularCourseInfoResponse.java
  src/main/java/umc/catchy/domain/course/service/CourseService.java
Labels: feat

#132 [feature] 장소 평점/리뷰 전체 보기
  src/main/java/umc/catchy/domain/place/api/PlaceController.java
  src/main/java/umc/catchy/domain/placeReview/converter/PlaceReviewConverter.java
  src/main/java/umc/catchy/domain/placeReview/dao/PlaceReviewRepository.java
  src/main/java/umc/catchy/domain/placeReview/dao/PlaceReviewRepositoryCustom.java
  src/main/java/umc/catchy/domain/placeReview/dao/PlaceReviewRepositoryImpl.java
  src/main/java/umc/catchy/domain/placeReview/domain/PlaceReview.java
  src/main/java/umc/catchy/domain/placeReview/dto/response/PostPlaceReviewResponse.java
  src/main/java/umc/catchy/domain/placeReview/service/PlaceReviewService.java
  src/main/java/umc/catchy/global/common/response/status/ErrorStatus.java
  src/main/java/umc/catchy/global/config/querydsl/QueryDslConfig.java
Labels: feat

#125 [feature] 장소 방문 체크 구현
  src/main/java/umc/catchy/domain/course/api/CourseController.java
  src/main/java/umc/catchy/domain/course/service/CourseService.java
  src/main/java/umc/catchy/domain/mapping/placeCourse/api/PlaceCourseController.java
  src/main/java/umc/catchy/domain/mapping/placeCourse/dto/response/PlaceInfoResponse.java
  src/main/java/umc/catchy/domain/mapping/placeCourse/service/PlaceCourseService.java
  src/main/java/umc/catchy/domain/mapping/placeVisit/converter/PlaceVisitConverter.java
  src/main/java/umc/catchy/domain/mapping/placeVisit/dao/PlaceVisitRepository.java
  src/main/java/umc/catchy/domain/mapping/placeVisit/domain/PlaceVisit.java
  src/main/java/umc/catchy/domain/mapping/placeVisit/dto/response/PlaceVisitedResponse.java
  src/main/java/umc/catchy/domain/mapping/placeVisit/service/PlaceVisitService.java
  src/main/java/umc/catchy/domain/place/converter/PlaceConverter.java
  src/main/java/umc/catchy/domain/placeReview/converter/PlaceReviewConverter.java
  src/main/java/umc/catchy/domain/placeReview/dto/response/PostPlaceReviewResponse.java
  src/main/java/umc/catchy/domain/placeReview/service/PlaceReviewService.java
  src/main/java/umc/catchy/global/common/response/status/ErrorStatus.java
Labels: feat

#151 [feat] 리뷰 신고/삭제 API
  src/main/java/umc/catchy/domain/courseReviewImage/dao/CourseReviewImageRepository.java
  src/main/java/umc/catchy/domain/placeReviewImage/dao/PlaceReviewImageRepository.java
  src/main/java/umc/catchy/domain/reviewReport/api/ReviewReportController.java
  src/main/java/umc/catchy/domain/reviewReport/converter/ReviewReportConverter.java
  src/main/java/umc/catchy/domain/reviewReport/dao/ReviewReportRepository.java
  src/main/java/umc/catchy/domain/reviewReport/domain/ReviewReport.java
  src/main/java/umc/catchy/domain/reviewReport/domain/ReviewType.java
  src/main/java/umc/catchy/domain/reviewReport/dto/request/PostReviewReportRequest.java
  src/main/java/umc/catchy/domain/reviewReport/dto/response/DeleteReviewResponse.java
  src/main/java/umc/catchy/domain/reviewReport/dto/response/PostReviewReportResponse.java
  src/main/java/umc/catchy/domain/reviewReport/service/ReviewReportService.java
  src/main/java/umc/catchy/global/common/response/status/ErrorStatus.java
Labels: feat

#156 [chore] healthCheck API
  src/main/java/umc/catchy/global/config/security/SecurityConfig.java
  src/main/java/umc/catchy/infra/aws/health/HealthCheckController.java
Labels: chore

#155 [fix] AI 추천 코스 생성 시 member_course 테이블에 저장
  src/main/java/umc/catchy/domain/course/service/CourseService.java
  src/main/java/umc/catchy/domain/mapping/memberCourse/domain/MemberCourse.java
Labels: fix

#149 [fix] 장소 카테고리 설정 로직 수정
  src/main/java/umc/catchy/domain/category/dao/CategoryRepository.java
  src/main/java/umc/catchy/domain/place/service/PlaceService.java
Labels: fix

#158 [fix] 회원 탈퇴 로직 수정
  src/main/java/umc/catchy/domain/mapping/memberActivetime/dao/MemberActiveTimeRepository.java
  src/main/java/umc/catchy/domain/mapping/memberCategory/dao/MemberCategoryRepository.java
  src/main/java/umc/catchy/domain/mapping/memberCategoryVote/dao/MemberCategoryVoteRepository.java
  src/main/java/umc/catchy/domain/mapping/memberCourse/dao/MemberCourseRepository.java
  src/main/java/umc/catchy/domain/mapping/memberGroup/dao/MemberGroupRepository.java
  src/main/java/umc/catchy/domain/mapping/memberLocation/dao/MemberLocationRepository.java
  src/main/java/umc/catchy/domain/mapping/memberPlaceVote/dao/MemberPlaceVoteRepository.java
  src/main/java/umc/catchy/domain/mapping/memberStyle/dao/MemberStyleRepository.java
  src/main/java/umc/catchy/domain/member/api/MemberController.java
  src/main/java/umc/catchy/domain/member/service/MemberService.java
Labels: fix

#150 [feature] 코스 리뷰 전체 보기
  src/main/java/umc/catchy/domain/course/api/CourseController.java
  src/main/java/umc/catchy/domain/course/converter/CourseConverter.java
  src/main/java/umc/catchy/domain/courseReview/converter/CourseReviewConverter.java
  src/main/java/umc/catchy/domain/courseReview/dao/CourseReviewRepository.java
  src/main/java/umc/catchy/domain/courseReview/dao/CourseReviewRepositoryCustom.java
  src/main/java/umc/catchy/domain/courseReview/dao/CourseReviewRepositoryImpl.java
  src/main/java/umc/catchy/domain/courseReview/domain/CourseReview.java
  src/main/java/umc/catchy/domain/courseReview/dto/response/PostCourseReviewResponse.java
  src/main/java/umc/catchy/domain/courseReview/service/CourseReviewService.java
  src/main/java/umc/catchy/domain/mapping/memberCourse/domain/MemberCourse.java
Labels: feat

#165 [feature] 카테고리 다시 투표하기
  src/main/java/umc/catchy/domain/mapping/memberCategoryVote/dao/MemberCategoryVoteRepository.java
  src/main/java/umc/catchy/domain/vote/api/VoteController.java
  src/main/java/umc/catchy/domain/vote/service/VoteService.java
  src/main/java/umc/catchy/global/common/response/status/ErrorStatus.java
Labels: feat

#167 [fix] 홈 화면의 AI 코스 - "내 코스 조회"에서 제외
  src/main/java/umc/catchy/domain/course/api/CourseController.java
  src/main/java/umc/catchy/domain/course/service/CourseService.java
  src/main/java/umc/catchy/domain/course/service/GPTCourseService.java
  src/main/java/umc/catchy/domain/member/domain/Member.java
Labels: fix

#170 [feature] 내 리뷰 조회 API
  src/main/java/umc/catchy/domain/courseReview/dao/CourseReviewRepository.java
  src/main/java/umc/catchy/domain/courseReview/dao/CourseReviewRepositoryCustom.java
  src/main/java/umc/catchy/domain/courseReview/dao/CourseReviewRepositoryImpl.java
  src/main/java/umc/catchy/domain/placeReview/dao/PlaceReviewRepository.java
  src/main/java/umc/catchy/domain/placeReview/dao/PlaceReviewRepositoryCustom.java
  src/main/java/umc/catchy/domain/placeReview/dao/PlaceReviewRepositoryImpl.java
  src/main/java/umc/catchy/domain/reviewReport/api/ReviewReportController.java
  src/main/java/umc/catchy/domain/reviewReport/dto/response/MyPageReviewsResponse.java
  src/main/java/umc/catchy/domain/reviewReport/service/ReviewReportService.java
Labels: feat

#171 [fix] 장소리뷰 신고된 리뷰는 안보이도록 수정 및 방문날짜로 정렬하도록 버그 수정
  src/main/java/umc/catchy/domain/place/api/PlaceController.java
  src/main/java/umc/catchy/domain/placeReview/dao/PlaceReviewRepositoryCustom.java
  src/main/java/umc/catchy/domain/placeReview/dao/PlaceReviewRepositoryImpl.java
  src/main/java/umc/catchy/domain/placeReview/domain/PlaceReview.java
  src/main/java/umc/catchy/domain/placeReview/service/PlaceReviewService.java
Labels: feat, fix

#174 [fix] 코스 상세 정보 response에 북마크 여부 추가
  src/main/java/umc/catchy/domain/course/converter/CourseConverter.java
  src/main/java/umc/catchy/domain/course/dto/response/CourseInfoResponse.java
  src/main/java/umc/catchy/domain/course/service/CourseService.java
Labels: fix

#178 [fix] AI 추천 코스 응답 수정
  src/main/java/umc/catchy/CatchyApplication.java
  src/main/java/umc/catchy/domain/course/dto/response/GptCourseInfoResponse.java
  src/main/java/umc/catchy/domain/course/service/CourseService.java
  src/main/java/umc/catchy/domain/place/dao/PlaceCustomRepository.java
  src/main/java/umc/catchy/domain/place/dao/PlaceRepositoryImpl.java
Labels: fix

#181 [fix] 카테고리 별 장소 확인 무한스크롤
  src/main/java/umc/catchy/domain/place/dao/PlaceCustomRepository.java
  src/main/java/umc/catchy/domain/place/dao/PlaceRepositoryImpl.java
  src/main/java/umc/catchy/domain/vote/api/VoteController.java
  src/main/java/umc/catchy/domain/vote/dto/response/GroupPlaceResponse.java
  src/main/java/umc/catchy/domain/vote/service/VoteService.java
Labels: fix

#185 [chore] github-actions.yml 수정
  .github/workflows/github-actions.yml
Labels: chore

#183 [docs] 리드미 작성
  README.md
Labels: documentation

#187 [fix] 리뷰 신고 시 리뷰의 상태 변경
  src/main/java/umc/catchy/domain/courseReview/domain/CourseReview.java
  src/main/java/umc/catchy/domain/placeReview/domain/PlaceReview.java
  src/main/java/umc/catchy/domain/reviewReport/service/ReviewReportService.java
Labels: fix

#188 [fix] 캘린더 그룹 조회 수정
  src/main/java/umc/catchy/domain/group/api/GroupController.java
  src/main/java/umc/catchy/domain/group/service/GroupService.java
  src/main/java/umc/catchy/domain/mapping/memberGroup/dao/MemberGroupRepository.java
Labels: fix

#190 [fix] 마이페이지/리뷰 조회 API - 코스리뷰/장소리뷰 분리
  src/main/java/umc/catchy/domain/placeReview/dao/PlaceReviewRepositoryCustom.java
  src/main/java/umc/catchy/domain/placeReview/dao/PlaceReviewRepositoryImpl.java
  src/main/java/umc/catchy/domain/reviewReport/api/ReviewReportController.java
  src/main/java/umc/catchy/domain/reviewReport/dto/response/MyPageReviewsResponse.java
  src/main/java/umc/catchy/domain/reviewReport/service/ReviewReportService.java
Labels: fix

#191 [feature] 스케줄러 구현
  src/main/java/umc/catchy/CatchyApplication.java
  src/main/java/umc/catchy/domain/course/api/CourseController.java
  src/main/java/umc/catchy/domain/course/api/CourseSchedulerService.java
  src/main/java/umc/catchy/domain/course/dao/CourseRepository.java
  src/main/java/umc/catchy/domain/course/service/CourseService.java
  src/main/java/umc/catchy/domain/course/service/GPTCourseService.java
  src/main/java/umc/catchy/infra/aws/s3/AmazonS3Manager.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: feat

#194 [fix] 장소 상세 화면 response 변경
  src/main/java/umc/catchy/domain/mapping/placeCourse/dto/response/PlaceInfoDetail.java
  src/main/java/umc/catchy/domain/mapping/placeCourse/service/PlaceCourseService.java
  src/main/java/umc/catchy/domain/place/converter/PlaceConverter.java
Labels: fix

#192 [feature] redis를 통한 refreshToken 관리
  src/main/java/umc/catchy/domain/jwt/service/BlackTokenRedisService.java
  src/main/java/umc/catchy/domain/jwt/service/RedisTokenService.java
  src/main/java/umc/catchy/domain/mapping/placeLike/dao/PlaceLikeRepository.java
  src/main/java/umc/catchy/domain/mapping/placeVisit/dao/PlaceVisitRepository.java
  src/main/java/umc/catchy/domain/member/dao/MemberRepository.java
  src/main/java/umc/catchy/domain/member/domain/Member.java
  src/main/java/umc/catchy/domain/member/dto/response/SignUpResponse.java
  src/main/java/umc/catchy/domain/member/service/MemberService.java
  src/main/java/umc/catchy/global/common/response/status/ErrorStatus.java
  src/main/java/umc/catchy/global/util/JwtUtil.java
  src/main/java/umc/catchy/infra/config/security/JwtAuthenticationFilter.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: feat

#196 [refactor] 패키지 위치 변경
  src/main/java/umc/catchy/domain/course/service/CourseSchedulerService.java
  src/main/java/umc/catchy/domain/course/service/CourseService.java
Labels: refactor

#202 [fix] category 존재하지 않을 시 null 반환하도록 변경
  src/main/java/umc/catchy/domain/place/converter/PlaceConverter.java
Labels: fix

#200 [chore] 도커 이미지 사이즈 최적화
  Dockerfile
Labels: chore

#204 [feature] 장소이름/카테고리 검색을 통한 장소 검색
  src/main/java/umc/catchy/domain/mapping/placeCourse/dto/response/PlaceInfoContainRelevance.java
  src/main/java/umc/catchy/domain/mapping/placeCourse/dto/response/PlaceInfoContainRelevanceScoreSliceResponse.java
  src/main/java/umc/catchy/domain/place/api/PlaceController.java
  src/main/java/umc/catchy/domain/place/dao/PlaceCustomRepository.java
  src/main/java/umc/catchy/domain/place/dao/PlaceRepositoryImpl.java
  src/main/java/umc/catchy/domain/place/service/PlaceService.java
Labels: feat

#206 [fix] 마이페이지/코스 리뷰 조회 response 수정
  src/main/java/umc/catchy/domain/courseReview/dao/CourseReviewRepositoryImpl.java
  src/main/java/umc/catchy/domain/reviewReport/dto/response/MyPageReviewsResponse.java
Labels: fix

#208 [fix] github-actions.yml 수정
  .github/workflows/github-actions.yml
Labels: chore

#212 [fix] 마이페이지/코스 리뷰 조회 : 카테고리 중복 수정
  src/main/java/umc/catchy/domain/courseReview/dao/CourseReviewRepositoryImpl.java
  src/main/java/umc/catchy/domain/reviewReport/dto/response/MyPageReviewsResponse.java
Labels: fix

#211 [fix] 방문 체크 로직 / 코스(DIY) 평점 계산 로직 수정
  src/main/java/umc/catchy/domain/course/api/CourseController.java
  src/main/java/umc/catchy/domain/course/domain/Course.java
  src/main/java/umc/catchy/domain/course/service/CourseService.java
  src/main/java/umc/catchy/domain/mapping/memberCourse/domain/MemberCourse.java
  src/main/java/umc/catchy/domain/mapping/placeVisit/converter/PlaceVisitConverter.java
  src/main/java/umc/catchy/domain/mapping/placeVisit/dao/PlaceVisitRepository.java
  src/main/java/umc/catchy/domain/mapping/placeVisit/domain/PlaceVisit.java
  src/main/java/umc/catchy/domain/mapping/placeVisit/service/PlaceVisitService.java
  src/main/java/umc/catchy/domain/place/api/PlaceController.java
Labels: fix

#213 [feature] FCM 푸시알림 설정 및 기능 개발
  build.gradle
  src/main/java/umc/catchy/domain/course/service/CourseSchedulerService.java
  src/main/java/umc/catchy/domain/course/service/CourseService.java
  src/main/java/umc/catchy/domain/member/api/MemberController.java
  src/main/java/umc/catchy/domain/member/domain/FcmInfo.java
  src/main/java/umc/catchy/domain/member/domain/Member.java
  src/main/java/umc/catchy/domain/member/dto/request/UpdateFcmTokenRequest.java
  src/main/java/umc/catchy/domain/member/dto/response/SignUpResponse.java
  src/main/java/umc/catchy/domain/member/service/MemberService.java
  src/main/java/umc/catchy/domain/vote/service/VoteService.java
  src/main/java/umc/catchy/global/common/constants/FcmConstants.java
  src/main/java/umc/catchy/infra/config/fcm/FCMConfig.java
  src/main/java/umc/catchy/infra/config/fcm/FCMService.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: feat

#215 [fix] 리뷰 생성 시 isReported가 false가 되도록 수정
  src/main/java/umc/catchy/domain/courseReview/converter/CourseReviewConverter.java
  src/main/java/umc/catchy/domain/courseReview/domain/CourseReview.java
  src/main/java/umc/catchy/domain/placeReview/converter/PlaceReviewConverter.java
  src/main/java/umc/catchy/domain/placeReview/domain/PlaceReview.java
Labels: fix

#217 [refactor] 비동기 처리를 통한 장소 검색 속도 개선
  src/main/java/umc/catchy/domain/mapping/placeCourse/api/PlaceCourseController.java
  src/main/java/umc/catchy/domain/mapping/placeCourse/service/PlaceCourseService.java
  src/main/java/umc/catchy/global/config/security/SecurityConfig.java
Labels: refactor

#225 [fix] 장소 상세화면 response 수정
  src/main/java/umc/catchy/domain/mapping/placeCourse/dto/response/PlaceInfoDetail.java
  src/main/java/umc/catchy/domain/place/converter/PlaceConverter.java
Labels: fix

#222 [fix] 코스 상세 조회 : 각 장소 별 카테고리 response에 추가
  src/main/java/umc/catchy/domain/course/dto/response/CourseInfoResponse.java
  src/main/java/umc/catchy/domain/place/converter/PlaceConverter.java
Labels: fix

#227 [fix] OSRM Route 요청 url에 geometry 옵션 추가
  src/main/java/umc/catchy/infra/osrm/OsrmRequest.java
  src/main/java/umc/catchy/infra/osrm/OsrmResponse.java
  src/main/java/umc/catchy/infra/osrm/OsrmService.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: fix

#223 [fix] 코스 독립적으로 방문체크하는 로직 수정
  src/main/java/umc/catchy/domain/mapping/placeVisit/dao/PlaceVisitRepository.java
  src/main/java/umc/catchy/domain/mapping/placeVisit/service/PlaceVisitService.java
Labels: fix

#230 [fix] 장소 검색 response 수정
  src/main/java/umc/catchy/domain/mapping/placeCourse/dto/response/PlaceInfoPreview.java
  src/main/java/umc/catchy/domain/mapping/placeCourse/service/PlaceCourseService.java
  src/main/java/umc/catchy/domain/place/converter/PlaceConverter.java
Labels: fix

#228 [chore] 캐시 적용을 통한 빌드 시간 단축
  .github/workflows/github-actions.yml
  Dockerfile
Labels: chore

#232 [fix] SecurityConfig 수정
  src/main/java/umc/catchy/global/config/security/SecurityConfig.java
Labels: fix

#237 [fix] BigCategory enum 값 수정
  src/main/java/umc/catchy/domain/category/domain/BigCategory.java
Labels: fix

#238 [fix] LocationUtils Map 수정
  src/main/java/umc/catchy/domain/course/util/LocationUtils.java
Labels: fix

#242 [fix] 장소 관련 response 수정
  src/main/java/umc/catchy/domain/mapping/placeCourse/dto/response/PlaceInfoDetail.java
  src/main/java/umc/catchy/domain/mapping/placeCourse/service/PlaceCourseService.java
  src/main/java/umc/catchy/domain/place/converter/PlaceConverter.java
Labels: fix
